
title: CESIA
email:
description: >
  Supervisión, estudios técnicos y proyectos de ingeniería civil.
  Empresa constituida en la ciudad de Hermosillo, Sonora,
  integrada por un equipo de ingenieros especialistas capacitados.
baseurl: "" # the subpath of your site, e.g. /blog

# Build settings
markdown: kramdown
